version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: "InnowiseTask"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "8403"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - '5432:5432'
    volumes:
#      - empty initialization
#      - db:/var/lib/postgresql/data
#      - for kuber
#      - /d/Work/InnowisePreTraineeTask/db/init.sql.:/docker-entrypoint-initdb.d/create_tables.sql
      - ./db/init.sql.:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    image: appimage
    build:
      dockerfile: Dockerfile
      context: .
      target: runner
    expose:
      - 8081
    depends_on:
      - db
    ports:
      - "8081:8081"
    volumes:
#      for kuber
#      - /d/work/InnowisePreTraineeTask:/opt/app
      - .:/opt/app
volumes:
  db:
    driver: local