apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-app
  labels:
    app: go-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-k8s-app
  template:
    metadata:
      labels:
        app: go-k8s-app
    spec:
      containers:
        -   name: db
            image: postgres:15-alpine
            imagePullPolicy: Never
            ports:
              - containerPort: 5432
        -   name: app
            image: appimage
            imagePullPolicy: Never
            ports:
              -   containerPort: 8081