apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\denis\go\bin\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: NodePort
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
